
services:
  # 1. TRAEFIK (El Portero SSL)
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Redirecci칩n autom치tica HTTP -> HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # Configuraci칩n de Certificados (Let's Encrypt)
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=admin@serviglobal.co" # <--- TU EMAIL
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - app_net

  # 2. TU API (BACKEND)
  api:
    build: .
    container_name: retell_api
    restart: always
    depends_on:
      - redis
    volumes:
      - ./credentials:/app/credentials
    environment:
      - REDIS_URL=redis://retell_redis:6379/0
      # Las variables que leer치 del archivo .env del  servidor
      - WHATSAPP_TOKEN=${WHATSAPP_TOKEN}
      - WHATSAPP_PHONE_ID=${WHATSAPP_PHONE_ID}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    labels:
      - "traefik.enable=true"
      # CAMBIA ESTO POR TU SUBDOMINIO REAL
      - "traefik.http.routers.api.rule=Host(`demoinmobiliaria.serviglobal.co`)" 
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      
    networks:
      - app_net

  # 3. REDIS (BASE DE DATOS)
  redis:
    image: redis/redis-stack-server:latest
    container_name: retell_redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app_net

networks:
  app_net:

volumes:
  redis_data: